Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-1804"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false

  # config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 22080 
  config.vm.network "forwarded_port", guest: 22, host: 22022
  config.vm.network "forwarded_port", guest: 443, host: 22443  
  config.vm.network "forwarded_port", guest: 3306, host: 22306
  
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  #config.vm.provision "shell", inline: <<-SHELL
   #  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
    # systemctl restart sshd.service
  #SHELL
  
  #config.vm.provision :chef_solo do |chef|
    ##chef.add_recipe("java")
  #end
  
end
